### ISSUE TITLE
Fans crawling here rn

### ISSUE THREAD

**Issue by 3000IQPlay** [iTeqch/Experium-leak#1]

**Comment by iTeqch** [comment]
not really

**Comment by 3000IQPlay** [comment]
> not really

they are

**Comment by 3000IQPlay** [comment]
also why have u leaked it?

**Comment by iTeqch** [comment]
idk

**Comment by iTeqch** [comment]
i can delete it. If you want

**Comment by 3000IQPlay** [comment]
thats the best reason for "also why have u leaked it?"

**Comment by iTeqch** [comment]
Yes

**Comment by 3000IQPlay** [comment]
._.

**Comment by 3000IQPlay** [comment]
Atom is kinda weird ngl - Eralp232

**Comment by 3000IQPlay** [comment]
Not even a friend at this moment

**Comment by iTeqch** [comment]
we were never friends. Bro i have asked for help many times but nah. You never helped me.

**Comment by iTeqch** [comment]
> also why have u leaked it?

Do you want me to delete it?

**Comment by 3000IQPlay** [comment]
never asked for anything
